import type { ItemDef } from './contentDb'

export const DEFAULT_ITEMS: ItemDef[] = [
  {
    id: 'Mushrooms',
    name: 'Mushrooms',
    icon: { kind: 'emoji', value: '🍄' },
    tags: ['food'],
    feed: {
      hunger: 18,
      stamina: 6,
      hp: 4,
      statusChances: [
        { status: 'Blessed', pct: 4, onlySpecies: 'Mycyclops' },
        { status: 'Sick', pct: 6 },
      ],
    },
  },
  { id: 'Foodroot', name: 'Foodroot', icon: { kind: 'emoji', value: '🥕' }, tags: ['food'], feed: { hunger: 24, stamina: 6, hp: 10 } },
  {
    id: 'WaterbagEmpty',
    name: 'Waterbag (Empty)',
    icon: { kind: 'emoji', value: '🫙' },
    tags: ['container'],
    useOnPoi: { Well: { transformTo: 'WaterbagFull', toast: 'Filled the waterbag.' } },
  },
  { id: 'WaterbagFull', name: 'Waterbag (Full)', icon: { kind: 'emoji', value: '💧' }, tags: ['container', 'food'], feed: { hunger: 0, thirst: 30 } },
  {
    id: 'Stone',
    name: 'Stone',
    icon: { kind: 'emoji', value: '🪨' },
    tags: ['material', 'weapon', 'oneHand'],
    weapon: { baseDamage: 5, damageType: 'Blunt', damageStat: 'strength', staminaCost: 3 },
    equipSlots: ['handLeft', 'handRight'],
  },
  {
    id: 'Stick',
    name: 'Stick',
    icon: { kind: 'emoji', value: '🪵' },
    tags: ['material', 'weapon', 'oneHand'],
    weapon: { baseDamage: 4, damageType: 'Blunt', damageStat: 'agility', staminaCost: 2 },
    equipSlots: ['handLeft', 'handRight'],
  },
  {
    id: 'Club',
    name: 'Club',
    icon: { kind: 'emoji', value: '🏏' },
    tags: ['weapon', 'oneHand'],
    weapon: { baseDamage: 7, damageType: 'Blunt', damageStat: 'strength', staminaCost: 4 },
    equipSlots: ['handLeft', 'handRight'],
  },
  {
    id: 'Spear',
    name: 'Spear',
    icon: { kind: 'emoji', value: '🗡️' },
    tags: ['weapon', 'twoHand'],
    weapon: { baseDamage: 8, damageType: 'Pierce', damageStat: 'strength', staminaCost: 6 },
    equipSlots: ['handLeft', 'handRight'],
  },
  { id: 'IronKey', name: 'Iron key', icon: { kind: 'emoji', value: '🗝️' }, tags: ['quest'] },
  { id: 'BrassKey', name: 'Brass key', icon: { kind: 'emoji', value: '🗝️' }, tags: ['quest'] },
  // Remedies are edible so `feedCharacter` can apply cure effects then consume.
  { id: 'BandageStrip', name: 'Bandage strip', icon: { kind: 'emoji', value: '🩹' }, tags: ['food'], feed: { hunger: 0 } },
  { id: 'AntitoxinVial', name: 'Antitoxin vial', icon: { kind: 'emoji', value: '🧪' }, tags: ['food'], feed: { hunger: 0 } },
  { id: 'HerbPoultice', name: 'Herb poultice', icon: { kind: 'emoji', value: '🌿' }, tags: ['food'], feed: { hunger: 0 } },
  { id: 'ClothScrap', name: 'Cloth scrap', icon: { kind: 'emoji', value: '🧵' }, tags: ['material'] },
  { id: 'Twine', name: 'Twine', icon: { kind: 'emoji', value: '🪢' }, tags: ['material', 'tool'] },
  { id: 'HerbLeaf', name: 'Herb leaf', icon: { kind: 'emoji', value: '🍃' }, tags: ['material'] },
  { id: 'BitterHerb', name: 'Bitter herb', icon: { kind: 'emoji', value: '🌱' }, tags: ['material'] },
  { id: 'GlassVial', name: 'Glass vial', icon: { kind: 'emoji', value: '🧴' }, tags: ['material', 'container'] },
  { id: 'Chisel', name: 'Chisel', icon: { kind: 'emoji', value: '🪓' }, tags: ['tool', 'oneHand'], equipSlots: ['handLeft', 'handRight'] },
  {
    id: 'StoneShard',
    name: 'Stone shard',
    icon: { kind: 'emoji', value: '🪨' },
    tags: ['tool', 'weapon', 'oneHand'],
    weapon: { baseDamage: 5, damageType: 'Cut', damageStat: 'agility', staminaCost: 3, statusOnHit: [{ status: 'Bleeding', pct: 15, durationMs: 20_000 }] },
    equipSlots: ['handLeft', 'handRight'],
  },
  { id: 'Ash', name: 'Ash', icon: { kind: 'emoji', value: '⚫️' }, tags: ['material'] },
  { id: 'Sulfur', name: 'Sulfur', icon: { kind: 'emoji', value: '🟡' }, tags: ['material'] },
  {
    id: 'Firebolt',
    name: 'Firebolt',
    icon: { kind: 'emoji', value: '🔥' },
    tags: ['weapon', 'oneHand'],
    weapon: { baseDamage: 10, damageType: 'Fire', consumesOnUse: true, staminaCost: 5 },
    equipSlots: ['handLeft', 'handRight'],
  },
  {
    id: 'Fireshield',
    name: 'Fireshield',
    icon: { kind: 'emoji', value: '🛡️' },
    tags: ['tool', 'oneHand'],
    equipSlots: ['handLeft', 'handRight'],
    combatShield: { fireResistBonusPct: 0.28, staminaCost: 4, shieldTurns: 3, consumesOnUse: true },
  },
  {
    id: 'Sling',
    name: 'Sling',
    icon: { kind: 'emoji', value: '🪃' },
    tags: ['weapon', 'tool', 'oneHand'],
    weapon: { baseDamage: 5, damageType: 'Blunt', damageStat: 'agility', staminaCost: 4 },
    equipSlots: ['handLeft', 'handRight'],
  },
  {
    id: 'Bolas',
    name: 'Bolas',
    icon: { kind: 'emoji', value: '🪢' },
    tags: ['weapon', 'tool', 'oneHand'],
    weapon: { baseDamage: 5, damageType: 'Blunt', damageStat: 'agility', staminaCost: 4 },
    equipSlots: ['handLeft', 'handRight'],
  },
  {
    id: 'Bow',
    name: 'Bow',
    icon: { kind: 'emoji', value: '🏹' },
    tags: ['weapon', 'tool', 'twoHand'],
    weapon: { baseDamage: 6, damageType: 'Pierce', damageStat: 'agility', staminaCost: 6 },
    equipSlots: ['handLeft', 'handRight'],
  },
  {
    id: 'WoolCap',
    name: 'Wool cap',
    icon: { kind: 'emoji', value: '🧢' },
    tags: ['hat'],
    equipSlots: ['head'],
  },
  {
    id: 'HerbCirclet',
    name: 'Herb circlet',
    icon: { kind: 'emoji', value: '🌼' },
    tags: ['hat'],
    equipSlots: ['head'],
  },
  {
    id: 'SporeCap',
    name: 'Spore cap',
    icon: { kind: 'emoji', value: '🍄' },
    tags: ['hat'],
    equipSlots: ['head'],
  },
  { id: 'MortarMeal', name: 'Mortar meal', icon: { kind: 'emoji', value: '🥣' }, tags: ['food'], feed: { hunger: 12, stamina: 4 } },
  { id: 'Flourball', name: 'Flourball', icon: { kind: 'emoji', value: '🍞' }, tags: ['food'], feed: { hunger: 22, stamina: 8, hp: 4 } },
  { id: 'HerbTea', name: 'Herb tea', icon: { kind: 'emoji', value: '🫖' }, tags: ['food', 'container'], feed: { hunger: 0, thirst: 18, stamina: 3 } },

  // Content expansion: materials, food, light, tools.
  { id: 'Moss', name: 'Moss', icon: { kind: 'emoji', value: '🌿' }, tags: ['material', 'food'], feed: { hunger: 0 } },
  { id: 'Slime', name: 'Slime', icon: { kind: 'emoji', value: '🫧' }, tags: ['material'] },
  { id: 'Mucus', name: 'Mucus', icon: { kind: 'emoji', value: '💧' }, tags: ['material'] },
  { id: 'Mold', name: 'Mold', icon: { kind: 'emoji', value: '🦠' }, tags: ['material'] },
  { id: 'Fungus', name: 'Fungus', icon: { kind: 'emoji', value: '🍄' }, tags: ['material', 'food'], feed: { hunger: 6, stamina: 2 } },
  { id: 'Bone', name: 'Bone', icon: { kind: 'emoji', value: '🦴' }, tags: ['material'] },
  { id: 'Claw', name: 'Claw', icon: { kind: 'emoji', value: '🦞' }, tags: ['material'] },
  { id: 'Tooth', name: 'Tooth', icon: { kind: 'emoji', value: '🦷' }, tags: ['material'] },
  { id: 'Salt', name: 'Salt', icon: { kind: 'emoji', value: '🧂' }, tags: ['material', 'food'], feed: { hunger: 0 } },
  { id: 'Gem', name: 'Gem', icon: { kind: 'emoji', value: '💎' }, tags: ['material', 'quest'] },
  { id: 'Sweetroot', name: 'Sweetroot', icon: { kind: 'emoji', value: '🍠' }, tags: ['food', 'material'], feed: { hunger: 10, stamina: 3 } },
  { id: 'Glowbug', name: 'Glowbug', icon: { kind: 'emoji', value: '✨' }, tags: ['material'] },
  { id: 'Grubling', name: 'Grubling', icon: { kind: 'emoji', value: '🐛' }, tags: ['food', 'material'], feed: { hunger: 8, stamina: 2 } },
  { id: 'BobrJuice', name: 'Bobr juice', icon: { kind: 'emoji', value: '🧃' }, tags: ['food', 'container', 'material'], feed: { hunger: 2, thirst: 14, stamina: 4 } },
  { id: 'Figurine', name: 'Figurine', icon: { kind: 'emoji', value: '🗿' }, tags: ['quest'] },
  { id: 'Torch', name: 'Torch', icon: { kind: 'emoji', value: '🔥' }, tags: ['tool', 'oneHand'], equipSlots: ['handLeft', 'handRight'] },
  { id: 'Headlamp', name: 'Headlamp', icon: { kind: 'emoji', value: '🔦' }, tags: ['tool', 'hat'], equipSlots: ['head'] },
  { id: 'Lantern', name: 'Lantern', icon: { kind: 'emoji', value: '🏮' }, tags: ['tool', 'oneHand'], equipSlots: ['handLeft', 'handRight'] },
  {
    id: 'Staff',
    name: 'Staff',
    icon: { kind: 'emoji', value: '🪄' },
    tags: ['weapon', 'twoHand'],
    weapon: { baseDamage: 7, damageType: 'Blunt', damageStat: 'strength', staminaCost: 5 },
    equipSlots: ['handLeft', 'handRight'],
  },
  {
    id: 'AttunedStaff',
    name: 'Attuned staff',
    icon: { kind: 'emoji', value: '✴️' },
    tags: ['weapon', 'twoHand', 'quest'],
    weapon: { baseDamage: 9, damageType: 'Thunder', damageStat: 'intelligence', staminaCost: 6 },
    equipSlots: ['handLeft', 'handRight'],
  },
  {
    id: 'BoneSpike',
    name: 'Bone spike',
    icon: { kind: 'emoji', value: '🦴' },
    tags: ['weapon', 'oneHand'],
    weapon: { baseDamage: 6, damageType: 'Pierce', damageStat: 'agility', staminaCost: 4 },
    equipSlots: ['handLeft', 'handRight'],
  },
  { id: 'MushedRoot', name: 'Mushed root', icon: { kind: 'emoji', value: '🥣' }, tags: ['food'], feed: { hunger: 14, stamina: 5, hp: 3 } },
  { id: 'Shroomcake', name: 'Shroomcake', icon: { kind: 'emoji', value: '🎂' }, tags: ['food'], feed: { hunger: 20, stamina: 8, hp: 4 } },
  { id: 'Shroompie', name: 'Shroompie', icon: { kind: 'emoji', value: '🥧' }, tags: ['food'], feed: { hunger: 26, stamina: 10, hp: 6 } },
  { id: 'Rootsoup', name: 'Rootsoup', icon: { kind: 'emoji', value: '🍲' }, tags: ['food'], feed: { hunger: 18, stamina: 6, hp: 8, thirst: 4 } },
  { id: 'RootsoupSalted', name: 'Salted rootsoup', icon: { kind: 'emoji', value: '🍲' }, tags: ['food'], feed: { hunger: 22, stamina: 10, hp: 12, thirst: 6 } },
  { id: 'PreservedGrub', name: 'Preserved grub', icon: { kind: 'emoji', value: '🥫' }, tags: ['food'], feed: { hunger: 16, stamina: 8, hp: 4 } },

  // Hive/Swarm ecosystem (Elfenstein_notes).
  { id: 'Hive', name: 'Hive', icon: { kind: 'emoji', value: '🪺' }, tags: ['tool'] },
  { id: 'SwarmQueen', name: 'Swarm Queen', icon: { kind: 'emoji', value: '👑' }, tags: ['quest'] },
  { id: 'SwarmBasket', name: 'Swarm basket', icon: { kind: 'emoji', value: '🧺' }, tags: ['tool'] },
  { id: 'CapturedSwarm', name: 'Captured swarm', icon: { kind: 'emoji', value: '🫧' }, tags: ['tool'] },
]

