import type { ItemDef } from './contentDb'

export const DEFAULT_ITEMS: ItemDef[] = [
  {
    id: 'Mushrooms',
    name: 'Mushrooms',
    icon: {
      kind: 'emoji',
      value: '🍄',
      tintFilter: 'grayscale(0.38) sepia(0.22) saturate(0.48) brightness(1.14) contrast(1.03)',
      displayScale: 0.82,
    },
    tags: ['food'],
    feed: {
      hunger: 26,
      stamina: 6,
      hp: 4,
      statusChances: [
        { status: 'Blessed', pct: 4, onlySpecies: 'Mycyclops' },
        { status: 'Sick', pct: 6 },
      ],
    },
  },
  { id: 'Foodroot', name: 'Foodroot', icon: { kind: 'emoji', value: '🥕' }, tags: ['food'], feed: { hunger: 34, stamina: 6, hp: 10 } },
  {
    id: 'WaterbagEmpty',
    name: 'Waterbag (Empty)',
    icon: { kind: 'emoji', value: '🫙' },
    tags: ['container'],
    useOnPoi: { Well: { transformTo: 'WaterbagFull', toast: 'Filled the waterbag.' } },
  },
  {
    id: 'WaterbagFull',
    name: 'Waterbag (Full)',
    icon: { kind: 'emoji', value: '💧' },
    tags: ['container', 'food'],
    feed: { hunger: 0, thirst: 30, leaveEmptyAs: 'WaterbagEmpty' },
  },
  {
    id: 'WaterskinEmpty',
    name: 'Waterskin (Empty)',
    icon: { kind: 'emoji', value: '🧴' },
    tags: ['container'],
    useOnPoi: { Well: { transformTo: 'WaterskinFull', toast: 'Filled the waterskin.' } },
  },
  {
    id: 'WaterskinFull',
    name: 'Waterskin (Full)',
    icon: { kind: 'emoji', value: '💦' },
    tags: ['container', 'food'],
    feed: { hunger: 0, thirst: 20, leaveEmptyAs: 'WaterskinEmpty' },
  },
  {
    id: 'TravelFlaskEmpty',
    name: 'Travel flask (Empty)',
    icon: { kind: 'emoji', value: '⚗️' },
    tags: ['container'],
    useOnPoi: { Well: { transformTo: 'TravelFlaskFull', toast: 'Filled the travel flask.' } },
  },
  {
    id: 'TravelFlaskFull',
    name: 'Travel flask (Full)',
    icon: { kind: 'emoji', value: '🥤' },
    tags: ['container', 'food'],
    feed: { hunger: 0, thirst: 26, leaveEmptyAs: 'TravelFlaskEmpty' },
  },
  {
    id: 'Stone',
    name: 'Stone',
    icon: { kind: 'emoji', value: '🪨' },
    tags: ['material', 'weapon', 'oneHand'],
    weapon: { baseDamage: 5, damageType: 'Blunt', damageStat: 'strength', staminaCost: 3 },
    equipSlots: ['handLeft', 'handRight'],
    durabilityMax: 50,
  },
  {
    id: 'Stick',
    name: 'Stick',
    icon: { kind: 'emoji', value: '🪵' },
    tags: ['material', 'weapon', 'oneHand'],
    weapon: { baseDamage: 4, damageType: 'Blunt', damageStat: 'agility', staminaCost: 2 },
    equipSlots: ['handLeft', 'handRight'],
    durabilityMax: 45,
  },
  {
    id: 'Club',
    name: 'Club',
    icon: { kind: 'emoji', value: '🏏', rotateDeg: 90 },
    tags: ['weapon', 'oneHand'],
    weapon: { baseDamage: 7, damageType: 'Blunt', damageStat: 'strength', staminaCost: 4 },
    equipSlots: ['handLeft', 'handRight'],
    durabilityMax: 72,
  },
  {
    id: 'Spear',
    name: 'Spear',
    icon: { kind: 'emoji', value: '🗡️', rotateDeg: 180 },
    tags: ['weapon', 'twoHand'],
    weapon: { baseDamage: 8, damageType: 'Pierce', damageStat: 'strength', staminaCost: 6 },
    equipSlots: ['handLeft', 'handRight'],
    durabilityMax: 88,
  },
  { id: 'IronKey', name: 'Iron key', icon: { kind: 'emoji', value: '🗝️' }, tags: ['quest'] },
  {
    id: 'BrassKey',
    name: 'Brass key',
    icon: { kind: 'emoji', value: '🗝️', tintFilter: 'hue-rotate(142deg) saturate(2.55) contrast(1.12)' },
    tags: ['quest'],
  },
  // Remedies are edible so `feedCharacter` can apply cure effects then consume.
  { id: 'BandageStrip', name: 'Bandage strip', icon: { kind: 'emoji', value: '🩹' }, tags: ['remedy', 'material'] },
  { id: 'AntitoxinVial', name: 'Antitoxin vial', icon: { kind: 'emoji', value: '🧪' }, tags: ['food'], feed: { hunger: 0 } },
  { id: 'HerbPoultice', name: 'Herb poultice', icon: { kind: 'emoji', value: '🌿' }, tags: ['food'], feed: { hunger: 0 } },
  { id: 'ClothScrap', name: 'Cloth scrap', icon: { kind: 'emoji', value: '🧵' }, tags: ['material'] },
  { id: 'Twine', name: 'Twine', icon: { kind: 'emoji', value: '🪢' }, tags: ['material', 'tool'] },
  { id: 'HerbLeaf', name: 'Herb leaf', icon: { kind: 'emoji', value: '🍃' }, tags: ['material'] },
  { id: 'BitterHerb', name: 'Bitter herb', icon: { kind: 'emoji', value: '🌱' }, tags: ['material'] },
  {
    id: 'GlassVial',
    name: 'Glass vial',
    icon: { kind: 'emoji', value: '🧴', tintFilter: 'hue-rotate(228deg) saturate(2.55) brightness(1.06) contrast(1.12)' },
    tags: ['material', 'container'],
  },
  {
    id: 'Chisel',
    name: 'Chisel',
    icon: { kind: 'emoji', value: '🪓' },
    tags: ['tool', 'oneHand'],
    equipSlots: ['handLeft', 'handRight'],
    durabilityMax: 80,
  },
  {
    id: 'StoneShard',
    name: 'Stone shard',
    icon: { kind: 'emoji', value: '🪨', tintFilter: 'hue-rotate(-118deg) saturate(2.5) contrast(1.12)', displayScale: 0.9 },
    tags: ['tool', 'weapon', 'oneHand'],
    weapon: { baseDamage: 5, damageType: 'Cut', damageStat: 'agility', staminaCost: 3, statusOnHit: [{ status: 'Bleeding', pct: 15, durationMs: 20_000 }] },
    equipSlots: ['handLeft', 'handRight'],
    durabilityMax: 64,
  },
  { id: 'Ash', name: 'Ash', icon: { kind: 'emoji', value: '⚫️' }, tags: ['material'] },
  { id: 'Sulfur', name: 'Sulfur', icon: { kind: 'emoji', value: '🟡' }, tags: ['material'] },
  {
    id: 'Firebolt',
    name: 'Firebolt',
    icon: {
      kind: 'emoji',
      value: '🔥',
      tintFilter: 'hue-rotate(162deg) saturate(2.55) brightness(1.04) contrast(1.12)',
    },
    tags: ['weapon', 'oneHand'],
    weapon: { baseDamage: 10, damageType: 'Fire', consumesOnUse: true, staminaCost: 5 },
    equipSlots: ['handLeft', 'handRight'],
  },
  {
    id: 'Fireshield',
    name: 'Fireshield',
    icon: { kind: 'emoji', value: '🛡️' },
    tags: ['tool', 'oneHand'],
    equipSlots: ['handLeft', 'handRight'],
    combatShield: { fireResistBonusPct: 0.28, staminaCost: 4, shieldTurns: 3, consumesOnUse: true },
  },
  {
    id: 'Sling',
    name: 'Sling',
    icon: { kind: 'emoji', value: '🪃' },
    tags: ['weapon', 'tool', 'oneHand'],
    weapon: { baseDamage: 4, damageType: 'Blunt', damageStat: 'agility', staminaCost: 3 },
    equipSlots: ['handLeft', 'handRight'],
    durabilityMax: 58,
  },
  {
    id: 'Bolas',
    name: 'Bolas',
    icon: { kind: 'emoji', value: '🪢', tintFilter: 'hue-rotate(158deg) saturate(2.45) contrast(1.12)', displayScale: 1.06 },
    tags: ['weapon', 'tool', 'oneHand'],
    weapon: {
      baseDamage: 5,
      damageType: 'Blunt',
      damageStat: 'agility',
      staminaCost: 4,
      statusOnHit: [{ status: 'Rooted', pct: 12, durationMs: 12_000 }],
    },
    equipSlots: ['handLeft', 'handRight'],
    durabilityMax: 62,
  },
  {
    id: 'Bow',
    name: 'Bow',
    icon: { kind: 'emoji', value: '🏹' },
    tags: ['weapon', 'tool', 'twoHand'],
    weapon: { baseDamage: 7, damageType: 'Pierce', damageStat: 'agility', staminaCost: 7 },
    equipSlots: ['handLeft', 'handRight'],
    durabilityMax: 84,
  },
  {
    id: 'WoolCap',
    name: 'Wool cap',
    icon: {
      kind: 'emoji',
      value: '🧢',
      tintFilter: 'sepia(0.55) saturate(1.22) hue-rotate(14deg) brightness(0.89) contrast(1.09)',
      displayScale: 1.04,
    },
    tags: ['hat'],
    equipSlots: ['head'],
  },
  {
    id: 'HerbCirclet',
    name: 'Herb circlet',
    icon: { kind: 'emoji', value: '🌼' },
    tags: ['hat'],
    equipSlots: ['head'],
  },
  {
    id: 'SporeCap',
    name: 'Spore cap',
    icon: { kind: 'emoji', value: '🍄', tintFilter: 'sepia(0.58) hue-rotate(12deg) saturate(2.8) contrast(1.16) brightness(0.88)', displayScale: 1.08 },
    tags: ['hat'],
    equipSlots: ['head'],
  },
  {
    id: 'ShellHat',
    name: 'Shell hat',
    icon: { kind: 'emoji', value: '🐚', tintFilter: 'hue-rotate(-152deg) saturate(2.5) contrast(1.14)', displayScale: 1.04 },
    tags: ['hat'],
    equipSlots: ['head'],
  },
  {
    id: 'NestHat',
    name: 'Nest hat',
    icon: {
      kind: 'emoji',
      value: '🪹',
      tintFilter: 'sepia(0.58) saturate(1.32) hue-rotate(8deg) brightness(0.88) contrast(1.1)',
    },
    tags: ['hat'],
    equipSlots: ['head'],
  },
  { id: 'MortarMeal', name: 'Mortar meal', icon: { kind: 'emoji', value: '🥣' }, tags: ['food'], feed: { hunger: 12, stamina: 4 } },
  { id: 'Flourball', name: 'Flourball', icon: { kind: 'emoji', value: '🍞' }, tags: ['food'], feed: { hunger: 22, stamina: 8, hp: 4 } },
  {
    id: 'HerbTea',
    name: 'Herb tea',
    icon: { kind: 'emoji', value: '🫖' },
    tags: ['food', 'container'],
    feed: { hunger: 0, thirst: 18, stamina: 3, primaryStamina: true },
  },

  // Content expansion: materials, food, light, tools.
  {
    id: 'Moss',
    name: 'Moss',
    icon: { kind: 'emoji', value: '🌿', tintFilter: 'hue-rotate(168deg) saturate(2.55) brightness(0.88) contrast(1.12)' },
    tags: ['material', 'food'],
    feed: { hunger: 0 },
  },
  { id: 'Slime', name: 'Slime', icon: { kind: 'emoji', value: '🫧' }, tags: ['material'] },
  {
    id: 'Mucus',
    name: 'Mucus',
    icon: { kind: 'emoji', value: '💧', tintFilter: 'hue-rotate(-158deg) saturate(2.5) contrast(1.14)', displayScale: 0.9 },
    tags: ['material'],
  },
  { id: 'Mold', name: 'Mold', icon: { kind: 'emoji', value: '🦠' }, tags: ['material'] },
  {
    id: 'Fungus',
    name: 'Fungus',
    icon: {
      kind: 'emoji',
      value: '🍄',
      tintFilter: 'hue-rotate(-172deg) saturate(2.5) brightness(0.86) contrast(1.12)',
      displayScale: 0.88,
    },
    tags: ['material', 'food'],
    feed: { hunger: 6, stamina: 2 },
  },
  { id: 'Bone', name: 'Bone', icon: { kind: 'emoji', value: '🦴' }, tags: ['material'] },
  { id: 'Claw', name: 'Claw', icon: { kind: 'emoji', value: '🦞' }, tags: ['material'] },
  { id: 'Tooth', name: 'Tooth', icon: { kind: 'emoji', value: '🦷' }, tags: ['material'] },
  { id: 'Salt', name: 'Salt', icon: { kind: 'emoji', value: '🧂' }, tags: ['material', 'food'], feed: { hunger: 0 } },
  { id: 'Gem', name: 'Gem', icon: { kind: 'emoji', value: '💎' }, tags: ['material', 'quest'] },
  {
    id: 'Sweetroot',
    name: 'Sweetroot',
    icon: { kind: 'emoji', value: '🍠' },
    tags: ['food', 'material'],
    feed: { hunger: 10, stamina: 3 },
    useOnPoi: {
      Shrine: { consumeOffering: true, blessPartyMs: 25_000, toast: 'The shrine accepts the offering. A faint warmth settles on the party.' },
    },
  },
  {
    id: 'Glowbug',
    name: 'Glowbug',
    icon: { kind: 'emoji', value: '✨' },
    tags: ['material', 'tool', 'oneHand'],
    equipSlots: ['handLeft', 'handRight'],
    playerLight: 'glowbug',
  },
  { id: 'Grubling', name: 'Grubling', icon: { kind: 'emoji', value: '🐛' }, tags: ['food', 'material'], feed: { hunger: 8, stamina: 2 } },
  {
    id: 'Snailing',
    name: 'Snailing',
    icon: { kind: 'emoji', value: '🐌' },
    tags: ['food', 'material'],
    feed: { hunger: 9, stamina: 2, hp: 1 },
  },
  {
    id: 'SnailingShell',
    name: 'Snailing shell',
    icon: { kind: 'emoji', value: '🐚' },
    tags: ['material'],
  },
  {
    id: 'BobrJuice',
    name: 'Bobr juice',
    icon: { kind: 'emoji', value: '🧃' },
    tags: ['food', 'container', 'material'],
    feed: { hunger: 2, thirst: 14, stamina: 4, primaryStamina: true },
  },
  { id: 'Figurine', name: 'Figurine', icon: { kind: 'emoji', value: '🗿' }, tags: ['quest'] },
  {
    id: 'Torch',
    name: 'Torch',
    icon: {
      kind: 'emoji',
      value: '🔥',
      tintFilter: 'sepia(0.58) hue-rotate(-28deg) saturate(2.65) brightness(1.08) contrast(1.14)',
      displayScale: 1.06,
    },
    tags: ['tool', 'oneHand'],
    equipSlots: ['handLeft', 'handRight'],
    playerLight: 'torch',
  },
  {
    id: 'Headlamp',
    name: 'Headlamp',
    icon: { kind: 'emoji', value: '🏮', flipVertical: true },
    tags: ['tool', 'hat'],
    equipSlots: ['head'],
    playerLight: 'headlamp',
  },
  {
    id: 'Lantern',
    name: 'Lantern',
    icon: { kind: 'emoji', value: '🔦', rotateDeg: 180 },
    tags: ['tool', 'oneHand'],
    equipSlots: ['handLeft', 'handRight'],
    playerLight: 'lantern',
  },
  {
    id: 'Staff',
    name: 'Staff',
    icon: { kind: 'emoji', value: '🪄' },
    tags: ['weapon', 'twoHand'],
    weapon: { baseDamage: 7, damageType: 'Blunt', damageStat: 'strength', staminaCost: 5 },
    equipSlots: ['handLeft', 'handRight'],
    durabilityMax: 76,
  },
  {
    id: 'AttunedStaff',
    name: 'Attuned staff',
    icon: { kind: 'emoji', value: '✴️' },
    tags: ['weapon', 'twoHand', 'quest'],
    weapon: { baseDamage: 9, damageType: 'Thunder', damageStat: 'intelligence', staminaCost: 6 },
    equipSlots: ['handLeft', 'handRight'],
    durabilityMax: 96,
  },
  {
    id: 'BoneSpike',
    name: 'Bone spike',
    icon: { kind: 'emoji', value: '🦴', tintFilter: 'hue-rotate(128deg) saturate(2.45) contrast(1.16)', displayScale: 1.08 },
    tags: ['weapon', 'oneHand'],
    weapon: { baseDamage: 6, damageType: 'Pierce', damageStat: 'agility', staminaCost: 4 },
    equipSlots: ['handLeft', 'handRight'],
    durabilityMax: 54,
  },
  {
    id: 'Rapier',
    name: 'Rapier',
    icon: { kind: 'emoji', value: '🪡', tintFilter: 'hue-rotate(-6deg) saturate(0.9)', displayScale: 0.92, rotateDeg: 180 },
    tags: ['weapon', 'oneHand'],
    weapon: { baseDamage: 8, damageType: 'Pierce', damageStat: 'agility', staminaCost: 5 },
    equipSlots: ['handLeft', 'handRight'],
    durabilityMax: 86,
  },
  {
    id: 'ShellSpike',
    name: 'Shell spike',
    icon: { kind: 'emoji', value: '🐚', tintFilter: 'hue-rotate(118deg) saturate(2.5) contrast(1.14)', displayScale: 0.88 },
    tags: ['weapon', 'oneHand'],
    weapon: { baseDamage: 5, damageType: 'Pierce', damageStat: 'agility', staminaCost: 4 },
    equipSlots: ['handLeft', 'handRight'],
    durabilityMax: 52,
  },
  {
    id: 'MushedRoot',
    name: 'Mushed root',
    icon: { kind: 'emoji', value: '🥣', tintFilter: 'sepia(0.65) hue-rotate(-108deg) saturate(2.45) contrast(1.12)', displayScale: 0.94 },
    tags: ['food'],
    feed: { hunger: 14, stamina: 5, hp: 3 },
  },
  { id: 'Shroomcake', name: 'Shroomcake', icon: { kind: 'emoji', value: '🎂' }, tags: ['food'], feed: { hunger: 20, stamina: 8, hp: 4 } },
  {
    id: 'Shroompie',
    name: 'Shroompie',
    icon: { kind: 'emoji', value: '🥧' },
    tags: ['food'],
    feed: { hunger: 26, stamina: 10, hp: 6, primaryStamina: true },
  },
  { id: 'Rootsoup', name: 'Rootsoup', icon: { kind: 'emoji', value: '🍲' }, tags: ['food'], feed: { hunger: 18, stamina: 6, hp: 8, thirst: 4 } },
  {
    id: 'RootsoupSalted',
    name: 'Salted rootsoup',
    icon: { kind: 'emoji', value: '🍲', tintFilter: 'hue-rotate(148deg) saturate(2.55) brightness(1.1) contrast(1.12)', displayScale: 1.05 },
    tags: ['food'],
    feed: { hunger: 22, stamina: 10, hp: 12, thirst: 6 },
  },
  { id: 'PreservedGrub', name: 'Preserved grub', icon: { kind: 'emoji', value: '🥫' }, tags: ['food'], feed: { hunger: 16, stamina: 8, hp: 4 } },
  {
    id: 'PickledSnailing',
    name: 'Pickled snailing',
    icon: { kind: 'emoji', value: '🥫', tintFilter: 'hue-rotate(118deg) saturate(2.5) contrast(1.12)', displayScale: 0.94 },
    tags: ['food'],
    feed: { hunger: 15, stamina: 7, hp: 4 },
  },

  // Mold branch + paperdoll slots (feet / clothing / accessory).
  {
    id: 'SnailSlimePaste',
    name: 'Snail-slime paste',
    icon: { kind: 'emoji', value: '🫗', tintFilter: 'hue-rotate(172deg) saturate(2.55) contrast(1.14)', displayScale: 0.93 },
    tags: ['material', 'food'],
    feed: { hunger: 0 },
  },
  { id: 'SporePaste', name: 'Spore paste', icon: { kind: 'emoji', value: '🫗' }, tags: ['material', 'food'], feed: { hunger: 0 } },
  {
    id: 'SporeStew',
    name: 'Spore stew',
    icon: { kind: 'emoji', value: '🍜' },
    tags: ['food'],
    feed: {
      hunger: 16,
      thirst: 8,
      stamina: 5,
      hp: 6,
      statusChances: [
        { status: 'Spored', pct: 7 },
        { status: 'Sick', pct: 5 },
      ],
    },
  },
  {
    id: 'GemCharm',
    name: 'Gem charm',
    icon: { kind: 'emoji', value: '📿' },
    tags: ['tool', 'quest'],
    equipSlots: ['accessory'],
  },
  {
    id: 'ShellCharm',
    name: 'Shell charm',
    icon: { kind: 'emoji', value: '📿', tintFilter: 'hue-rotate(-162deg) saturate(2.5) contrast(1.14)', displayScale: 0.96 },
    tags: ['tool'],
    equipSlots: ['accessory'],
  },
  {
    id: 'MossWrap',
    name: 'Moss wrap',
    icon: { kind: 'emoji', value: '🧣' },
    tags: ['tool'],
    equipSlots: ['clothing'],
  },
  {
    id: 'MossSandals',
    name: 'Moss sandals',
    icon: { kind: 'emoji', value: '🩴' },
    tags: ['tool'],
    equipSlots: ['feet'],
  },

  // Phase 2: crafting breadth, remedies, drink.
  {
    id: 'BrinedSpore',
    name: 'Brined spore',
    icon: { kind: 'emoji', value: '🥫', tintFilter: 'hue-rotate(-132deg) saturate(2.45) contrast(1.12)', displayScale: 0.92 },
    tags: ['food', 'material'],
    feed: { hunger: 6, stamina: 2, hp: 2, statusChances: [{ status: 'Sick', pct: 4 }] },
  },
  {
    id: 'SmolderBundle',
    name: 'Smolder bundle',
    icon: {
      kind: 'emoji',
      value: '🔥',
      tintFilter: 'hue-rotate(-38deg) saturate(2.7) brightness(0.9) contrast(1.14)',
      displayScale: 0.9,
    },
    tags: ['weapon', 'tool', 'oneHand'],
    weapon: { baseDamage: 6, damageType: 'Fire', damageStat: 'agility', consumesOnUse: true, staminaCost: 4 },
    equipSlots: ['handLeft', 'handRight'],
  },
  {
    id: 'RiverTonic',
    name: 'River tonic',
    icon: { kind: 'emoji', value: '🍶' },
    tags: ['food', 'container', 'material'],
    feed: { hunger: 0, thirst: 12, stamina: 5, statusChances: [{ status: 'Drowsy', pct: 6 }] },
  },
  { id: 'CoolingPoultice', name: 'Cooling poultice', icon: { kind: 'emoji', value: '🧊' }, tags: ['food'], feed: { hunger: 0 } },
  { id: 'DryWrap', name: 'Dry wrap', icon: { kind: 'emoji', value: '🧻' }, tags: ['food'], feed: { hunger: 0 } },

  // Crafting tools, deployable campfire, roasted outputs (campfire PoI).
  {
    id: 'Flint',
    name: 'Flint',
    icon: { kind: 'emoji', value: '✳️' },
    tags: ['material', 'tool', 'oneHand'],
    equipSlots: ['handLeft', 'handRight'],
  },
  {
    id: 'CampfireKit',
    name: 'Campfire kit',
    icon: { kind: 'emoji', value: '🪵', tintFilter: 'hue-rotate(138deg) saturate(2.5) contrast(1.12)', displayScale: 0.9 },
    tags: ['tool', 'material'],
  },
  {
    id: 'IronPot',
    name: 'Stone cookpot',
    icon: { kind: 'emoji', value: '🍳' },
    tags: ['tool'],
  },
  {
    id: 'Kettle',
    name: 'Kettle',
    icon: { kind: 'emoji', value: '🫖', tintFilter: 'hue-rotate(-138deg) saturate(2.5) contrast(1.12)', displayScale: 1.07 },
    tags: ['tool', 'container'],
  },
  {
    id: 'RoastMushrooms',
    name: 'Roast mushrooms',
    icon: {
      kind: 'emoji',
      value: '🍄',
      tintFilter: 'grayscale(1) brightness(0.36) contrast(1.3)',
      displayScale: 1.06,
    },
    tags: ['food'],
    feed: { hunger: 22, stamina: 8, hp: 6, statusChances: [{ status: 'Sick', pct: 3 }] },
  },
  {
    id: 'RoastFoodroot',
    name: 'Roast foodroot',
    icon: { kind: 'emoji', value: '🥕', tintFilter: 'sepia(0.62) hue-rotate(-108deg) saturate(2.45) contrast(1.12)', displayScale: 1.05 },
    tags: ['food'],
    feed: { hunger: 30, stamina: 8, hp: 12 },
  },
  {
    id: 'RoastGrub',
    name: 'Roast grub',
    icon: { kind: 'emoji', value: '🍖' },
    tags: ['food'],
    feed: { hunger: 18, stamina: 10, hp: 6 },
  },
  {
    id: 'RoastSnailing',
    name: 'Roast snailing',
    icon: { kind: 'emoji', value: '🍖', tintFilter: 'hue-rotate(132deg) sepia(0.48) saturate(2.5) contrast(1.14)', displayScale: 0.92 },
    tags: ['food'],
    feed: { hunger: 17, stamina: 9, hp: 6 },
  },
  {
    id: 'RoastFungus',
    name: 'Roast fungus',
    icon: { kind: 'emoji', value: '🍄' },
    tags: ['food'],
    feed: { hunger: 12, stamina: 5, hp: 4 },
  },

  {
    id: 'KuratkoEgg',
    name: 'Kuratko egg',
    icon: { kind: 'emoji', value: '🥚' },
    tags: ['food', 'material'],
    feed: { hunger: 10, stamina: 3, hp: 2, statusChances: [{ status: 'Sick', pct: 4 }] },
  },
  {
    id: 'RoastKuratkoEgg',
    name: 'Roast Kuratko egg',
    icon: { kind: 'emoji', value: '🥚', tintFilter: 'sepia(0.62) hue-rotate(108deg) saturate(2.45) brightness(1.08) contrast(1.12)', displayScale: 1.02 },
    tags: ['food'],
    feed: { hunger: 18, stamina: 7, hp: 5 },
  },
  {
    id: 'BoiledKuratkoEgg',
    name: 'Boiled Kuratko egg',
    icon: { kind: 'emoji', value: '🥚', tintFilter: 'hue-rotate(-148deg) saturate(2.5) contrast(1.14)', displayScale: 1.02 },
    tags: ['food'],
    feed: { hunger: 17, stamina: 6, hp: 6 },
  },
  {
    id: 'HerbKuratkoOmelette',
    name: 'Herb Kuratko omelette',
    icon: { kind: 'emoji', value: '🍳', tintFilter: 'hue-rotate(152deg) saturate(2.55) contrast(1.12)', displayScale: 1.04 },
    tags: ['food'],
    feed: { hunger: 28, stamina: 10, hp: 8 },
  },

  {
    id: 'Bahno',
    name: 'Bahno',
    icon: { kind: 'emoji', value: '🟤', tintFilter: 'sepia(0.35) brightness(0.92)', displayScale: 0.9 },
    tags: ['material', 'food'],
    feed: { hunger: 0, hp: 8 },
  },

  // Hive/Swarm ecosystem (Elfenstein_notes).
  {
    id: 'Hive',
    name: 'Hive',
    icon: { kind: 'emoji', value: '🏐' },
    tags: ['tool'],
  },
  { id: 'SwarmQueen', name: 'Swarm Queen', icon: { kind: 'emoji', value: '👑' }, tags: ['quest'] },
  { id: 'SwarmBasket', name: 'Swarm basket', icon: { kind: 'emoji', value: '🧺' }, tags: ['tool'] },
  {
    id: 'CapturedSwarm',
    name: 'Captured swarm',
    icon: { kind: 'emoji', value: '🫧', tintFilter: 'hue-rotate(158deg) saturate(2.55) contrast(1.14)', displayScale: 1.08 },
    tags: ['tool'],
  },

  // Slime phial / Wurglepup capture (parallel to Swarm basket flow).
  {
    id: 'SlimePhial',
    name: 'Slime phial',
    icon: { kind: 'emoji', value: '🧪', tintFilter: 'hue-rotate(-168deg) saturate(2.5) brightness(1.05) contrast(1.12)', displayScale: 0.96 },
    tags: ['tool'],
  },
  {
    id: 'CapturedSlime',
    name: 'Captured slime',
    icon: { kind: 'emoji', value: '🫧', tintFilter: 'hue-rotate(-138deg) saturate(2.5) brightness(0.9) contrast(1.14)', displayScale: 1.02 },
    tags: ['tool'],
  },

  // Glowbug jar: crafted dim hand light + optional Shrine offering (Kuratko / Snailord loot supplies parts).
  {
    id: 'GlowbugJar',
    name: 'Glowbug jar',
    icon: { kind: 'emoji', value: '🍯', tintFilter: 'hue-rotate(12deg) saturate(2.35) brightness(1.05) contrast(1.1)', displayScale: 0.95 },
    tags: ['material', 'tool', 'oneHand'],
    equipSlots: ['handLeft', 'handRight'],
    playerLight: 'glowbug',
    useOnPoi: {
      Shrine: {
        consumeOffering: true,
        blessPartyMs: 15_000,
        toast: 'Fireflies lift from the jar and scatter; a brief calm settles on the party.',
      },
    },
  },
]

