import type { FloorType } from '../../procgen/types'
import type { ItemDefId } from '../types'

/** Former chest + barrel/crate union: default “general dungeon” pool. */
const LOOT_BASELINE: ItemDefId[] = [
  'Stick',
  'Stone',
  'Mushrooms',
  'Foodroot',
  'BandageStrip',
  'AntitoxinVial',
  'HerbPoultice',
  'Chisel',
  'ClothScrap',
  'Twine',
  'HerbLeaf',
  'BitterHerb',
  'GlassVial',
  'StoneShard',
  'Ash',
  'Sulfur',
  'Club',
  'MortarMeal',
  'HerbTea',
  'WaterbagEmpty',
  'WoolCap',
  'HerbCirclet',
  'SporeCap',
  'Sling',
  'Bolas',
  'BobrJuice',
]

function uniq(ids: readonly ItemDefId[]): ItemDefId[] {
  return Array.from(new Set(ids))
}

/**
 * Chest, barrel, and crate loot by dungeon skin (`GameState.floor.floorType`).
 * Deterministic roll in `poi.ts` uses `floor.seed` + `poiId` + `:chest:` / `:container:` namespace.
 */
export const STORAGE_POI_LOOT_DEF_IDS_BY_FLOOR: Record<FloorType, readonly ItemDefId[]> = {
  Dungeon: LOOT_BASELINE,
  Cave: uniq([
    'Mushrooms',
    'Moss',
    'Fungus',
    'Slime',
    'Foodroot',
    'BobrJuice',
    'Glowbug',
    'Stone',
    'Stick',
    'WaterbagEmpty',
    'GlassVial',
    'Club',
    'Ash',
    'HerbLeaf',
    'BandageStrip',
    'ClothScrap',
    'Twine',
    'WoolCap',
    'SporeCap',
    'HerbTea',
    'MortarMeal',
    'Chisel',
    'StoneShard',
    'Sulfur',
  ]),
  Ruins: uniq([
    'Stone',
    'StoneShard',
    'Bone',
    'Salt',
    'BitterHerb',
    'Ash',
    'Stick',
    'Club',
    'Chisel',
    'ClothScrap',
    'MortarMeal',
    'GlassVial',
    'Foodroot',
    'Mushrooms',
    'Twine',
    'HerbLeaf',
    'WaterbagEmpty',
    'BandageStrip',
    'HerbPoultice',
    'BobrJuice',
    'Sling',
  ]),
  Jungle: uniq([
    'Mushrooms',
    'Fungus',
    'Foodroot',
    'Slime',
    'Twine',
    'ClothScrap',
    'HerbLeaf',
    'BitterHerb',
    'BobrJuice',
    'WaterbagEmpty',
    'Stone',
    'Stick',
    'Sling',
    'Bolas',
    'SporeCap',
    'MortarMeal',
    'Moss',
    'GlassVial',
    'Glowbug',
    'Sweetroot',
    'BandageStrip',
    'AntitoxinVial',
  ]),
  LivingBio: uniq([
    'Mushrooms',
    'Fungus',
    'Slime',
    'Moss',
    'Mucus',
    'SporeCap',
    'HerbPoultice',
    'AntitoxinVial',
    'GlassVial',
    'Foodroot',
    'HerbLeaf',
    'BitterHerb',
    'MortarMeal',
    'WaterbagEmpty',
    'ClothScrap',
    'Twine',
    'Stone',
    'Stick',
    'BandageStrip',
    'HerbTea',
    'BobrJuice',
    'Glowbug',
  ]),
  Bunker: uniq([
    'Salt',
    'MortarMeal',
    'GlassVial',
    'Stone',
    'StoneShard',
    'Ash',
    'Sulfur',
    'Chisel',
    'Club',
    'Stick',
    'Foodroot',
    'WaterbagEmpty',
    'Glowbug',
    'Twine',
    'ClothScrap',
    'HerbLeaf',
    'BandageStrip',
  ]),
  Catacombs: uniq([
    'Bone',
    'BobrJuice',
    'Salt',
    'BitterHerb',
    'Stone',
    'StoneShard',
    'HerbPoultice',
    'AntitoxinVial',
    'GlassVial',
    'Mushrooms',
    'ClothScrap',
    'Twine',
    'WaterbagEmpty',
    'Ash',
    'Stick',
    'Foodroot',
    'HerbLeaf',
    'MortarMeal',
    'HerbTea',
    'Sulfur',
    'Glowbug',
    'Moss',
  ]),
  Golem: uniq([
    'Stone',
    'StoneShard',
    'Sulfur',
    'Ash',
    'Chisel',
    'Club',
    'GlassVial',
    'Stick',
    'HerbTea',
    'Foodroot',
    'WaterbagEmpty',
    'Mushrooms',
    'Gem',
    'Twine',
  ]),
  Palace: uniq([
    'ClothScrap',
    'Twine',
    'Foodroot',
    'Figurine',
    'GlassVial',
    'HerbLeaf',
    'HerbTea',
    'WoolCap',
    'HerbCirclet',
    'Sweetroot',
    'Stone',
    'Stick',
    'Mushrooms',
    'WaterbagEmpty',
    'BandageStrip',
    'MortarMeal',
    'Salt',
    'Gem',
    'SporeCap',
    'BobrJuice',
  ]),
}

/** Union of all floor pools (procgen content audit, allowlists). */
export const PROCgen_ALL_STORAGE_POI_LOOT_DEF_IDS: ItemDefId[] = uniq(
  (Object.keys(STORAGE_POI_LOOT_DEF_IDS_BY_FLOOR) as FloorType[]).flatMap((k) => [...STORAGE_POI_LOOT_DEF_IDS_BY_FLOOR[k]]),
)
